apiVersion: apps/v1
kind: Deployment
metadata: 
  name: shop-client
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: shop-client
  template:
    metadata:
      labels:
        app: shop-client
    spec:
      containers:
      - name: shop-client
        imagePullPolicy: Always
        image: 634996749830.dkr.ecr.us-east-1.amazonaws.com/dummy-test:4
        ports:
        - containerPort: 80
