apiVersion: apps/v1
kind: Deployment
metadata: 
  name: order
spec:
  replicas: 1
  selectors:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      serviceAccountName: order-service
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "aws-secrets"
      containers:
        - name: order-service
        image: 634996749830.dkr.ecr.us-east-1.amazonaws.com/orders-service
        ports:
          - containerPort: 8081
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: SHOP_DATABASE_URL
          - name: BUCKET_NAME
            value: "image-bucket-c82ce065-20230906115510897800000002"
          - name: BUCKET_REGION
            value: "us-east-1" 
          - name: TOPIC_ARN
            value: "arn:aws:sns:us-east-1:634996749830:dev-topic"
