apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: arn:aws:secretsmanager:us-east-1:634996749830:secret:SHOP_DATABASE_URL-bLqQMQ
